### PR TITLE
TC-3867 clean up missing travel

### PR DESCRIPTION
**Pull request by eliottwiener-thirdchannel**
This feature was no longer being used, and removing it it saved me some effort rewriting tests on the backend.

### CODE REVIEW

**Comment by sasha-3C** [comment]
So is this PR only related to the first commit that you made? Is all of the other stuff just commits that haven't been merged into dev yet that don't need to be reviewed?

**Comment by eliottwiener-thirdchannel** [comment]
Fixed!

**Comment by sasha-3C** [comment]
Seems like this is just code cleanup - branch works fine for me and it doesn't look like the deletions affected anything. Have the tests on the backend for the outdated feature been removed? (or did they just not exist?)

**Comment by eliottwiener-thirdchannel** [comment]
The backend removals are in this PR https://github.com/RSV2/PennyPacker/pull/18

**Comment by sasha-3C** [comment]
Gotcha- lgtm then 👍

**Pull request merged**
