### PR TITLE
Updates to activity feed post footer

### PR DESCRIPTION
**Pull request by aliciasedlock**
**What:** Design cleanup and slight restructuring of the bottom of posts on the activity feed. Requires https://github.com/RSV2/ThirdChannel/pull/484

**Why:** Some cleanup was desired/needed prior to incoming work for the hashtag system.

**Jira:** https://thirdchannel.atlassian.net/browse/TC-5100

**Before (desktop & mobile)**
screen shot 2017-02-21 at 3 03 20 pm
screen shot 2017-02-21 at 3 03 58 pm

**After (desktop & mobile)**
screen shot 2017-02-21 at 3 00 40 pm
screen shot 2017-02-21 at 3 01 03 pm

### CODE REVIEW

**Comment by eliottwiener-thirdchannel** [comment]
I tried this out and I noticed two issues, which may or may not be related to my environment:

1. Unfollowing does not decrement the follow count

2. Adding and removing comments does not update the comment count

**Comment by aliciasedlock** [comment]
@eliottwiener-thirdchannel Cool, I'll check those out and see if it's a known thing/trying to fix it as part of this!

**Comment by aliciasedlock** [comment]
Looks like follows aren't being persisted on production either. Going to investigate a bit to see if it's a simple fix, otherwise I'll make a new ticket.

**Comment by eliottwiener-thirdchannel** [comment]
[Looks like the comments are not loading when in mobile width](https://media-api.atlassian.io/file/196ac14c-5487-4f5f-8da3-760ba952a619/binary?token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJiMTFjMjk0NC1mOWQyLTQwYmQtOTYzNi0wMzc5NjdjMTEwYjkiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOjE5NmFjMTRjLTU0ODctNGY1Zi04ZGEzLTc2MGJhOTUyYTYxOSI6WyJyZWFkIl19LCJleHAiOjE0ODc4MDg0ODcsIm5iZiI6MTQ4NzgwNzgyN30.bdw0GAIZs2lh-GL73dv1jongssdHi7QAdovOPmisTZE&client=b11c2944-f9d2-40bd-9636-037967c110b9&name=Screen+Shot+2017-02-21+at+3.01.03+PM.png)

**Comment by aliciasedlock** [comment]
@eliottwiener-thirdchannel That's current behavior, and is also behavior we want to keep via the design spec. https://projects.invisionapp.com/share/DRAECIWNT#/screens

**Pull request merged**
