### PR TITLE
TC-2169 - swapping the image modal with viewer w/ zoom capabilities

### PR DESCRIPTION
**Pull request by spullen**
Swapped out on:
* full report page
* store profile page (most recent images)
* store image gallery

Also see PR for ThirdChannel

### CODE REVIEW

**Comment by neolinkpsu** [comment]
seems pretty straight forward.  What browsers/mobile devices have we checked this out on?

**Comment by spullen** [comment]
so far just chrome. I'll take a look at it in some other browsers.

**Comment by spullen** [comment]
Works on firefox and safari. I'll check on a mobile device, less concerned about mobile for these pages though.

**Comment by spullen** [comment]
Tried on a mobile device, seemed to work just fine for me.

**Pull request merged**
